=== camenduru/style-tts-muse-talk-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "MuseTalk: Real-Time High Quality Lip Synchronization with Latent Space Inpainting",
      "author": "Yue Zhang, Minhao Liu, Zhaokang Chen, Bin Wu, Yingjie He, Chao Zhan, Wenjiang Zhou",
      "code": "https://github.com/TMElyralab/MuseTalk",
      "jupyter": "https://github.com/camenduru/MuseTalk-jupyter",
      "post": "https://x.com/camenduru/status/1800259963987558780",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/style-tts-muse-talk.ipynb",
      "tags": [
        "Text to Talking Video"
      ],
      "widget": "readme"
    },
    "prompt": {
      "type": "string",
      "description": "Text",
      "widget": "textarea"
    },
    "upload1": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "wav_input_url"
    },
    "wav_input_url": {
      "type": "string",
      "description": "WAV Input URL",
      "widget": "textarea"
    },
    "alpha": {
      "type": "number",
      "description": "TTS Alpha"
    },
    "beta": {
      "type": "number",
      "description": "TTS Beta"
    },
    "diffusion_steps": {
      "type": "integer",
      "description": "TTS Diffusion Steps"
    },
    "embedding_scale": {
      "type": "integer",
      "description": "TTS Embedding Scale"
    },
    "upload2": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "video_input_url"
    },
    "video_input_url": {
      "type": "string",
      "description": "Video Input URL",
      "widget": "textarea"
    },
    "bbox_shift": {
      "type": "integer",
      "description": "Bbox Shift"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/style-tts-muse-talk-tost/model.json
{
    "prompt": "In a small, forgotten village, there was a well that granted wishes but only if you whispered your deepest secret into its depths. One day, a young girl named Lily approached the well, desperate to save her sick mother. ",
    "wav_input_url": "https://huggingface.co/camenduru/MuseTalk/resolve/main/ash.wav",
    "alpha": 0.9,
    "beta": 0.9,
    "diffusion_steps": 10,
    "embedding_scale": 1,
    "video_input_url": "https://huggingface.co/camenduru/MuseTalk/resolve/main/video.mp4",
    "bbox_shift": 0
}
